create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  cedula text not null unique,
  name text,
  date date,
  plan text,
  plan_label text,
  status text not null default 'consulted',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_response_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists responses_updated_at on public.responses;
create trigger responses_updated_at
before update on public.responses
for each row execute function public.set_response_updated_at();

alter table public.responses enable row level security;
revoke all on public.responses from anon, authenticated;
